export const GALLERY = [
    {
      id: 0,
      name: "BALCONIES",
      avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/03/BalconyUnionClub3-390x260.jpg",
      featured: false,
    },
    {
        id: 1,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/03/BalconyUnionClub2-390x260.jpg",
        featured: false,
      },
      {
        id: 2,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/03/BalconyUnionClub1-300x200.jpg",
        featured: false,
      },
      {
        id: 3,
        name: "Club Room",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/club-room1-300x200.jpg",
        featured: false,
      },
      {
        id: 4,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/club-room2-300x200.jpg",
        featured: false,
      },
      {
        id: 5,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/club-room3-300x200.jpg",
        featured: false,
      },
      {
        id: 6,
        name: "Velvet Room",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/Velvet-Room2-300x200.jpg",
        featured: false,
      },
      {
        id: 7,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/Velvet-Room1-300x200.jpg",
        featured: false,
      },
      {
        id: 8,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/Velvet-Room3-300x200.jpg",
        featured: false,
      },
      {
        id: 9,
        name: "Sky Room",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/Sky-Room111-390x260.jpg",
        featured: false,
      },
      {
        id: 10,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/Sky-Room222-390x260.jpg",
        featured: false,
      },
      {
        id: 11,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/Sky-Room333-390x260.jpg",
        featured: false,
      },
      {
        id: 12,
        name: "Second Level",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/upstairs1-300x225.jpg",
        featured: false,
      },
      {
        id: 13,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/upstairs2-300x225.jpg",
        featured: false,
      },
      {
        id: 14,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/upstairs3-300x225.jpg",
        featured: false,
      },
      {
        id: 15,
        name: "Conference Rooms",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/03/UnionClubConferenceRoom1-300x200.jpg",
        featured: false,
      },
      {
        id: 16,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/03/UnionClubConferenceRoom2-300x200.jpg",
        featured: false,
      },
      {
        id: 17,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/03/UnionClubConferenceRoom3-300x200.jpg",
        featured: false,
      },
      {
        id: 18,
        name: "Great Hall",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/great-hall1-300x200.jpg",
        featured: false,
      },
      {
        id: 19,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/great-hall2-300x200.jpg",
        featured: false,
      },
      {
        id: 20,
        name:"",
        avatar_url: "https://unionclubtacoma.com/wp-content/uploads/2018/02/great-hall3-300x200.jpg",
        featured: false,
      },
    ]